def welcome():
    print( "               __  _______                       __           ")
    print( "              /  |/       \                     /  |          ")
    print( " _____  ____  $$/ $$$$$$$  |  ______    _______ $$ |  ______  ")
    print( "/     \/    \ /  |$$ |__$$ | /      \  /       |$$ | /      \ ")
    print( "$$$$$$ $$$$  |$$ |$$    $$<  $$$$$$  |/$$$$$$$/ $$ |/$$$$$$  |")
    print( "$$ | $$ | $$ |$$ |$$$$$$$  | /    $$ |$$ |      $$ |$$    $$ |")
    print( "$$ | $$ | $$ |$$ |$$ |  $$ |/$$$$$$$ |$$ \_____ $$ |$$$$$$$$/ ")
    print( "$$ | $$ | $$ |$$ |$$ |  $$ |$$    $$ |$$       |$$ |$$       |")
    print( "$$/  $$/  $$/ $$/ $$/   $$/  $$$$$$$/  $$$$$$$/ $$/  $$$$$$$/ ")
    print( "                                                              ")
    print( "                                                              ")
    print( "                                                              ")
    print("\nAuthor: Yashrajsinh Jadeja")
    print("\nGitHub: github.com/Yashrajsinh-Jadeja/")
    print("\nEmail: yashrajjadeja97@gmail.com")
    print("\nYashrajsinh-Jadeja/miRacle is licensed under the GNU General Public License v3.0. ")
    print("Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license.")
    print("Copyright and license notices must be preserved.")
    print("Contributors provide an express grant of patent rights.")
def welcome_flank():
    print("\n(c) miRacle flanking_updated_v3")
    print("\nThis program will generate precursors '.fasta' sequences accordingly as per the chosen flank length.")
    print("\nThe '.fasta' will look something like:")
    print("\n >ACCESSION")
    print(" LEFT FLANK SEQUENCE + MOTIF(the BLAST hit) + RIGHT FLANK SEQUENCE")
    print("\nNOTE: Individual '.fasta' files will be generated and not a multifasta because mfold does not accept multifasta format.\n")
    return
def welcome_fold():
    print("\n(c) miRacle fold_and_highlight_v3\n\n")
    print("\nSo you've finally made it this far! Hopefully you did not run into any erros while generating precursors.")
    print("\nAll the precursor sequences '.fasta' files generated were due to the inability of mfold parsing multifasta files.")
    print("\nThis script will start calculating folding energies of the precursor sequences and eventually highlight them accordingly where the miRNA falls in the sequence.")
    print("\nMake sure all precursor .fasta files (named precX.fasta) are present along with the motif_start and motif_end files.")
